# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #    routing_loader: true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  #    format_listener:
  #        rules:
  #            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: [ json ], fallback_format: ~, prefer_extension: false }
      - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
  service:
    router: router
    templating: templating
    serializer: null
    view_handler: fos_rest.view_handler.default
    inflector: fos_rest.inflector.doctrine
    validator: validator
#  serializer:
#    version: null
#    groups: ['api']
#    serialize_null: false
#  exception:
#    enabled: true
#    exception_controller: 'App\Controller\Api\ExceptionController::showAction'
#    codes:
#      SoapFault: 400
#      App\Exception\FeatureNotImplementedException: 404
#      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
#      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
#    messages:
#      SoapFault: true
#      App\Exception\FeatureNotImplementedException: true
#      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true
#      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true
